{% set name = "inifix" %}
{% set version = "7.0.0" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/inifix-{{ version }}.tar.gz
  sha256: f49dfe1beef23ba9bd5f46be698f7b1f8593eb83f21da029bb5f6cbf9f81cfcd

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - hatch-vcs
    - pip
  run:
    - python >={{ python_min }}

test:
  source_files:
    - tests
  imports:
    - inifix
  commands:
    - pip check
    - pytest -ra tests
  requires:
    - python {{ python_min }}
    - pip
    - pytest
    - hypothesis


about:
  summary: An I/O library for Pluto-style ini files.
  home: https://github.com/neutrinoceros/inifix
  license: GPL-2.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - neutrinoceros
