{% set name = "inifix" %}
{% set version = "5.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/inifix-{{ version }}.tar.gz
  sha256: d21b8a5652054ef90c6b4079559dc6dc04a76092e41aa14ba7849c039a6892a0

build:
  entry_points:
    - inifix-format = inifix.format:main
    - inifix-validate = inifix.validate:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.10
    - hatchling
    - pip
  run:
    - python >=3.10

test:
  source_files:
    - tests
  imports:
    - inifix
  commands:
    - pip check
    - inifix-format --help
    - inifix-validate --help
    - pytest -ra tests
  requires:
    - pip
    - pytest
    - hypothesis


about:
  summary: An I/O library for Pluto-style ini files.
  home: https://github.com/neutrinoceros/inifix
  license: GPL-2.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - neutrinoceros
