{% set name = "inifix" %}
{% set version = "5.0.4" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/inifix-{{ version }}.tar.gz
  sha256: 573be2064dcd6858c3beae2b19d2ff6aaa954c020be333cf9f51831ab8e9fee3

build:
  entry_points:
    - inifix-format = inifix.format:main
    - inifix-validate = inifix.validate:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}

test:
  source_files:
    - tests
  imports:
    - inifix
  commands:
    - pip check
    - inifix-format --help
    - inifix-validate --help
    - pytest -ra tests
  requires:
    - python {{ python_min }}
    - pip
    - pytest
    - hypothesis


about:
  summary: An I/O library for Pluto-style ini files.
  home: https://github.com/neutrinoceros/inifix
  license: GPL-2.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - neutrinoceros
