{% set name = "inifix" %}
{% set version = "6.1.2" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/inifix-{{ version }}.tar.gz
  sha256: b172f98b24180a401cdf6591a55d348c0ac5e80d4631445b59ba6f9c7e27f166

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - hatch-vcs
    - pip
  run:
    - python >={{ python_min }}
    - typing-extensions >=4.2.0  # only needed for Python 3.10
    - exceptiongroup >=1.0.0  # only needed for Python 3.10

test:
  source_files:
    - tests
  imports:
    - inifix
  commands:
    - pip check
    - pytest -ra tests
  requires:
    - python {{ python_min }}
    - pip
    - pytest
    - hypothesis


about:
  summary: An I/O library for Pluto-style ini files.
  home: https://github.com/neutrinoceros/inifix
  license: GPL-2.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - neutrinoceros
