schema_version: 1

context:
  name: inifix
  version: "7.0.1"
  python_min: "3.11"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/inifix-${{ version }}.tar.gz
  sha256: 1a396f77860f68ee0a1be77d7d2f1bb703583402f4019275a0ffe0acec44cef3

build:
  number: 1
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - hatch-vcs
    - pip
  run:
    - python >=${{ python_min }}

tests:
  - python:
      imports:
        - inifix
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"
  - files:
      source:
        - tests
    requirements:
      run:
        - python ${{ python_min }}.*
        - pip
        - pytest
        - hypothesis
        - runtime-introspect
    script:
      - pytest -ra tests

about:
  summary: An I/O library for Pluto-style ini files.
  license: GPL-2.0-or-later
  license_file: LICENSE
  homepage: https://github.com/neutrinoceros/inifix

extra:
  recipe-maintainers:
    - neutrinoceros
